export const AppRoute = {
  login: "/login",
  table: "/table",
  home: "/",
  importSettings: "/importSettings",
  edi: "/edi",
  member: "/member",
  account: "/account",
  customer: "/customer",
  dataSite: "/dataSite",
  association: "/association",
  principal: "/principal",
  representative: "/representative",
  experience: "/experience",
  importPreview: "/importPreview",
  templateConfig: "/templateConfig",
  corrections: "/corrections",
  currencyRate: "/currencyRate",
  importHistory: "/importHistory",
  alias: "/alias",
  mismatchedColumns: "/mismatchedColumns",
  processingNotes: "/processingNotes",
  help: "/help",
};
